export const teachers = [
  {
    id: 1,
    name: "S. Ruxshona",
    img: "https://inter-nation.uz/teachers/mr-timur.webp",
    subject: "eng",
    about:
      "2001-yil Andijonda tug'ilgan hozirda Cambridge universitetida byudjet asosida o'qiydi. Ielts 7.5. Eng tajribali o'qituvchilardan",
    schedule: {
      dushanba: [
        { time: "08:00", course: "Beginner", status: "green" },
        { time: "09:30", course: "Beginner", status: "yellow" },
        { time: "11:00", course: "Beginner", status: "red" },
        { time: "12:30", course: "Beginner", status: "green" },
        { time: "14:00", course: "Beginner", status: "yellow" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "yellow" },
      ],
      seshanba: [
        { time: "08:00", course: "Beginner", status: "red" },
        { time: "09:30", course: "Beginner", status: "green" },
        { time: "11:00", course: "Beginner", status: "yellow" },
        { time: "12:30", course: "Beginner", status: "red" },
        { time: "14:00", course: "Beginner", status: "yellow" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "green" },
      ],
      chorshanba: [
        { time: "08:00", course: "Beginner", status: "yellow" },
        { time: "09:30", course: "Beginner", status: "green" },
        { time: "11:00", course: "Beginner", status: "red" },
        { time: "12:30", course: "Beginner", status: "yellow" },
        { time: "14:00", course: "Beginner", status: "green" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "yellow" },
      ],
      payshanba: [
        { time: "08:00", course: "Beginner", status: "green" },
        { time: "09:30", course: "Beginner", status: "yellow" },
        { time: "11:00", course: "Beginner", status: "red" },
        { time: "12:30", course: "Beginner", status: "green" },
        { time: "14:00", course: "Beginner", status: "yellow" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "yellow" },
      ],
      juma: [
        { time: "08:00", course: "Beginner", status: "red" },
        { time: "09:30", course: "Beginner", status: "green" },
        { time: "11:00", course: "Beginner", status: "yellow" },
        { time: "12:30", course: "Beginner", status: "green" },
        { time: "14:00", course: "Beginner", status: "yellow" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "yellow" },
      ],
      shanba: [
        { time: "08:00", course: "Beginner", status: "yellow" },
        { time: "09:30", course: "Beginner", status: "green" },
        { time: "11:00", course: "Beginner", status: "red" },
        { time: "12:30", course: "Beginner", status: "yellow" },
        { time: "14:00", course: "Beginner", status: "green" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "yellow" },
      ],
    },
  },
  {
    id: 2,
    name: "A. Sardor",
    img: "https://inter-nation.uz/teachers/mr_olimjon.webp",
    subject: "eng",
    about:
      "1990-yil Toshkentda tug'ilgan. Oxford universitetini bitirgan. Ielts 8.5. Eng tajribali o'qituvchilardan",
    schedule: {
      dushanba: [
        { time: "08:00", course: "Beginner", status: "green" },
        { time: "09:30", course: "Beginner", status: "yellow" },
        { time: "11:00", course: "Beginner", status: "red" },
        { time: "12:30", course: "Beginner", status: "green" },
        { time: "14:00", course: "Beginner", status: "yellow" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "yellow" },
      ],
      seshanba: [
        { time: "08:00", course: "Beginner", status: "red" },
        { time: "09:30", course: "Beginner", status: "green" },
        { time: "11:00", course: "Beginner", status: "yellow" },
        { time: "12:30", course: "Beginner", status: "red" },
        { time: "14:00", course: "Beginner", status: "yellow" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "green" },
      ],
      chorshanba: [
        { time: "08:00", course: "Beginner", status: "yellow" },
        { time: "09:30", course: "Beginner", status: "green" },
        { time: "11:00", course: "Beginner", status: "red" },
        { time: "12:30", course: "Beginner", status: "yellow" },
        { time: "14:00", course: "Beginner", status: "green" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "yellow" },
      ],
      payshanba: [
        { time: "08:00", course: "Beginner", status: "green" },
        { time: "09:30", course: "Beginner", status: "yellow" },
        { time: "11:00", course: "Beginner", status: "red" },
        { time: "12:30", course: "Beginner", status: "green" },
        { time: "14:00", course: "Beginner", status: "yellow" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "yellow" },
      ],
      juma: [
        { time: "08:00", course: "Beginner", status: "red" },
        { time: "09:30", course: "Beginner", status: "green" },
        { time: "11:00", course: "Beginner", status: "yellow" },
        { time: "12:30", course: "Beginner", status: "green" },
        { time: "14:00", course: "Beginner", status: "yellow" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "yellow" },
      ],
      shanba: [
        { time: "08:00", course: "Beginner", status: "yellow" },
        { time: "09:30", course: "Beginner", status: "green" },
        { time: "11:00", course: "Beginner", status: "red" },
        { time: "12:30", course: "Beginner", status: "yellow" },
        { time: "14:00", course: "Beginner", status: "green" },
        { time: "15:30", course: "Beginner", status: "green" },
        { time: "17:00", course: "Beginner", status: "red" },
        { time: "18:30", course: "Beginner", status: "yellow" },
      ],
    },
  },
];
